import { setupWorker } from "msw/browser";

import { handlers } from "./handlers";

// Browser-side MSW worker, reusing the same `handlers` as the server (db.ts-backed).
// Used by Storybook (.storybook/preview) so network-touching stories can run against
// the mock backend instead of a live FastAPI. Started lazily — see `startMockWorker`.
// Requires `public/mockServiceWorker.js` (generated by `npx msw init public/`).
export const worker = setupWorker(...handlers);

let started = false;

/**
 * Start the worker once, tolerating environments where the service worker can't
 * register (e.g. the headless Vitest browser runner without the static SW served) —
 * a failure there must not break the story/test, so we swallow it.
 */
export async function startMockWorker(): Promise<void> {
  if (started || typeof window === "undefined") return;
  started = true;
  try {
    await worker.start({ onUnhandledRequest: "bypass", quiet: true });
  } catch {
    // No service worker available here — stories that don't touch the backend are unaffected.
  }
}
